### ISSUE TITLE
RequestVatInfo response: OracleConnection.ConnectionString is invalid (all of a sudden)

### ISSUE THREAD

**Issue by imneckro** [firebed/aade-mydata#17] opened 2024-03-23 16:40 UTC
Hello.
All of a sudden in RequestVatInfo  I am getting:
Client error: `GET https://mydatapi.aade.gr/myDATA/RequestVatInfo?dateFrom=01%2F02%2F2024&dateTo=29%2F02%2F2024` resulted in a `400 Bad Request` response: OracleConnection.ConnectionString is invalid

**Comment by firebed** [comment] 2024-03-23 17:55
It's probably a mydata issue. Please wait until the issue is resolved by itself.

**Comment by imneckro** [comment] 2024-03-24 18:14
Still aade tromparei....
8 RequestVatInfo out of 10 are failure (Bad Request response: OracleConnection.ConnectionString is invalid).

**Comment by firebed** [comment] 2024-03-25 02:58
Thanks for letting me know. I am closing this issue since it is not related to this repository.

**Closed by firebed** 2024-03-25 02:58 UTC
